### ISSUE TITLE
How should we distinguish between flags for regular expressions (if at all)?

### ISSUE THREAD

**Issue by johno** [regexhq/regexhq#11]
For example, I'm wondering if we should consider how we can expose global regexes vs non-global regexes with the `g` flag. Also, do we ever add other flags like `^` or `$`, etc?
##### There are a few ways to handle this

It could be exposed as an option:

``` javascript
var fooRegex = require('regex-foo');

'some string with stuff'.match(fooRegex({ global: true }));
```

Or, define multiple exports:

``` javascript
module.exports.global = globalFunctionRegex;
```

The simplest scenario is likely exporting `/justtheregex/`, allowing a dev to go the following route:

``` javascript
var fooRegex = require('regex-foo');

var globalFooRegex = new Regexp(fooRegex(), 'g');
'some string with stuff'.match(globalFooRegex);
```

**Comment by tunnckoCore** [comment]
> The simplest scenario is likely exporting /justtheregex/, allowing a dev to go the following route

Yep. Only if needed for specific scenario, we'll should set them, otherwise `allowing a dev`.
