### ISSUE TITLE
Basic CLI tool for auto commenting? lol

### ISSUE THREAD

**Issue by tunnckoCore** [regexhq/regexhq#14]
@regexps/owners 

Basic CLI tool that will check search (say by date?) for new repos whose contain `regexp` and `regex` keyword in their names. With some good template that will be our review. :)

for #9
Thoughts?

**Comment by sindresorhus** [comment]
Sounds like a horrible way to convince people to join.

I agree with having a template we can use as a base when we invite people though.

**Comment by yocontra** [comment]
No. Bad.

**Comment by yoshuawuyts** [comment]
:-1: energy's best spent on building more regexes. If anything, if you want to build a cli, then just build the cli and look if it's adopted. There's little need for big up-front design plans for writing simple modules.

**Comment by arthurvr** [comment]
A template comment, okay. Not a commenting bot :-1:

**Comment by dougwilson** [comment]
Yes, people don't want bot comments on their repos :) it would shed a negative image on this project for some people right off the bat.

**Comment by tunnckoCore** [comment]
> Yes, people don't want bot comments on their repos

With that "bot auto commenting" I mean, that thihs would be some basic cli, that will submit some good description as template from our accounts, not bot-specific account.

> If anything, if you want to build a cli, then just build the cli and look if it's adopted.

Yep. :)

**Comment by dougwilson** [comment]
> With that "bot auto commenting" I mean, that thihs would be some basic cli, that will submit some good description as template from our accounts, not bot-specific account.

Gotcha. As long as nothing is posted automatic, then I guess it's OK (i.e. a person reviewed it and it's coming from their own account).

**Comment by sindresorhus** [comment]
> With that "bot auto commenting" I mean, that thihs would be some basic cli, that will submit some good description as template from our accounts, not bot-specific account.

That's just completely overkill. We're not going to invite that many repos. Use your energy on the template text instead.

**Comment by tunnckoCore** [comment]
Okey, nevermind :)

I'll build the cli for myself. As of comment template it refers to #9
