### ISSUE TITLE
doi-regex

### ISSUE THREAD

**Issue by RichardLitt** [regexhq/regexhq#15]
Would you guys like https://github.com/BeagleLab/doi-regex here? I'd be happy to move it to this organization, or fork it in.

**Comment by yoshuawuyts** [comment]
@RichardLitt yeah, that'd be great! Wonder what others think.

/cc @tunnckoCore @jonschlinkert

**Comment by jonschlinkert** [comment]
:+1: awesome!

**Comment by RichardLitt** [comment]
Done!

**Comment by tunnckoCore** [comment]
Cool :+1:
