### ISSUE TITLE
Request for confirmation for `vimeo-regex` package

### ISSUE THREAD

**Issue by isRuslan** [regexhq/regexhq#18]
Hi everyone.
There is [vimeo-regex](https://github.com/isRuslan/vimeo-regex) for parsing `vimeo` video id.

``` js
var vimeoRegex = require('vimeo-regex');

// plain link
vimeoRegex().test('https://vimeo.com/62092214');
//=> true

// groups link
vimeoRegex().test('http://vimeo.com/groups/musicvideo/videos/126199390');
//=> true

// get video ID
vimeoRegex().exec('https://vimeo.com/62092214')[5];
//=> 62092214
```

Can you check this out, is it suitable for [regexps](https://github.com/regexps) organization?

**Comment by yoshuawuyts** [comment]
given that there's also a `youtube-regex`: sure, why not. There's probably someone out there that will find it useful at some point, and having it in the org might make it more discoverable (':

**Comment by tunnckoCore** [comment]
:+1: i'll review it tonight

**Comment by isRuslan** [comment]
There is also [coub-regex](https://github.com/isRuslan/coub-regex) to parse [coub.com](http://coub.com) video url.

Coub example:
<a href="http://coub.com/view/xou6" target="_blank">![gfwr1](https://cloud.githubusercontent.com/assets/2136166/8846264/375f1040-312e-11e5-8702-33a79229e16e.jpg)</a>

**Comment by tunnckoCore** [comment]
@isRuslan Ohh yea, really, cool!
Sorry for the delay, im just on the end of the university year here. I'll be okey in weekend!

This site looks pretty amazing, didn't know it!

**Comment by tunnckoCore** [comment]
@isRuslan good job! They looks good to me. I'll send you invite, feel free to transfer them :)

**Comment by isRuslan** [comment]
@tunnckoCore thanks! I moved `coub-regex` and `vimeo-regex` into `regexps` organization. I'll manage all the issues in these packages.

**Comment by tunnckoCore** [comment]
@isRuslan welcome! :)
