### ISSUE TITLE
Organization name change?

### ISSUE THREAD

**Issue by tunnckoCore** [regexhq/regexhq#20]
# to `regexhq`?

Because looks and sounds better, imo. Also that name is free on Github and Twitter.
I also tried to contact twitter account behind `regexps`, but no answer.

I dont want to just change it without no discussion.

**Comment by aloisdg** [comment]
Hello,

I personally prefer RegexHQ but I am an outsider here so...

**Comment by tunnckoCore** [comment]
@aloisdg thanks and no problem. :)

/cc @regexps/owners?

**Comment by yoshuawuyts** [comment]
I'm OK with either.

**Comment by tunnckoCore** [comment]
@regexhq/owners done :)
Remember to update your local repos if any and links that point directly to the previous org page `https://github.com/regexps` (if any, again).
