### ISSUE TITLE
greenskeeper noise

### ISSUE THREAD

**Issue by jonschlinkert** [regexhq/regexhq#23]
Is there a way to turn off the greenskeeper notifications? or to force greenskeeper to only do prs on minors/majors? 

edit: or maybe it is only doing minors/majors. in any case I'd love to find a way to not have my activity stream filled up with greenskeeper notifications when a devDependency gets updated. I don't see the need for this at all.

**Comment by tunnckoCore** [comment]
I'll disable it at all. But you definitely should try [RenovateApp](https://renovateapp.com/), it is pretty configurable and awesome. Support presets too. Biggest sell point is that it can automerge such updates, so you even don't need to know what happens and when :D Of course it respect semver ranges and etc, you just don't need to go manually hitting the button.

Not only that, but it has a whole lot benefits over GK.

**Comment by tunnckoCore** [comment]
Huh, it seems that I already disabled it :D

**Comment by jonschlinkert** [comment]
> But you definitely should try RenovateApp

It looks nice, thanks. fwiw, I don't really understand the reasoning behind automatically upgrading deps. It contradicts semver. Patches already get used without having to specify them in package.json, and automatically bumping a major can have downstream consequences.

For example, I'm going to have to update three packages this weekend because a dep bumped majors on their deps, but they didn't bump the major on their own package. As a result, the dependency tree has fat arrow functions being used, which breaks the engine in my libs. The point isn't about fat arrows, it's that people think that test coverage is the only thing that matters when updating deps, but it's not. Just a thought.
