### ISSUE TITLE
rename repo

### ISSUE THREAD

**Issue by jonschlinkert** [regexhq/regexhq#3]
how about if we rename this repo from logo-and-discussions to `general` or `meta` or whatever. just something that will make sense later too?

**Comment by tunnckoCore** [comment]
:+1: 
Yea, but idk what exactly.

**Comment by jonathanong** [comment]
once we hvae repos i can fork in badgeboard https://github.com/jshttp/jshttp.github.io style

**Comment by tunnckoCore** [comment]
@jonathanong yea, no prob. ;]

**Comment by tunnckoCore** [comment]
@contra @kevva @johnotander ping, share your thoughts for the name.

**Comment by johno** [comment]
I like both `general` and `meta` that were proposed.

**Comment by kevva** [comment]
`meta`

**Comment by tunnckoCore** [comment]
@regexps/owners another owners' comments? To go forward.

**Comment by jonschlinkert** [comment]
okay, we had two `meta` (stackoverflow style) and no other suggestions so I went with that.
