### ISSUE TITLE
Discussion about `code comments regexps`

### ISSUE THREAD

**Issue by tunnckoCore** [regexhq/regexhq#4]
Huh, lets start discuss this hard job and here.
@blakeembrey @sindresorhus @contra @jonschlinkert @mk-pmb
## Regex for code comments

Because of [jonschlinkert/strip-comments](https://github.com/jonschlinkert/strip-comments/) and [sindresorhus/comment-regex](https://github.com/sindresorhus/comment-regex) ... 
After all 2 days and 1 night came to this ones. lol
### Line comments regex

``` js
/(?:^|;\s?)\/\/([\S\s]+?)$/gm // pass almost everything, except indented line comments
```

``` js
/(?:^|[^:]\s?)\/\/([^'"]+?)$/gm // pass almost, except `code; // some "text" 'and' here`
```

``` js
/(?:^|[^:]\s?)\/\/([^;]+?)$/gm // pass almost, except `code; // wtf; yeah fails`
```

**and**

``` js
/(?:^|\s?)\/\/([^\\;]+?)$/gm
```

because of this use case

``` js
process.stdout.write('string literals: ');
console.dir({
  str0: '&apos;',
  str1: "&quot;",
  str2: ". // ' \\ . // ' \\ ."
});

process.stdout.write('RegExp literals: ');
console.dir({
  regexp0: /I'm the easiest in Chomsky hierarchy!/,
});
```

> So we have to decide which is the less used symbol, lol. This is the easiest way, imo.
> As @sindresorhus said it "it will never be totally foolproof as that impossible with just regex"
### Block comments regex

``` js
/(?:^|\s)(?:\/\*(?!\*?\/)(?:[\S\s]+?)\*\/)/gm
```
- not works for block comments in string variables
- `(?:^|\s)` and `(?!\*?\/)` save us from globstars and globstars-like `./globstar/path/to/**/*.js`, `./path/to/*/some/file.js`, `./glob/star/*/*like*/*.js`, `./some*/star/*/*path.js`
#### The question "How to determine block comment is in string?"

> Ideas for (better) regexes/solution and more use cases? Performance?

**using this fixture.js**

``` js
/**
 * multiline block comment
 */
var foo = function foo(oneline, /* block comment in */ func) {
  // indented oneline line comment
  var indented = 'variable'; // some "double-quotes" here

  /**
   * and indented
   * multiline
   * block comment
   */
  var and = true; // after var

  // indented with http://google.url.com
  var six = 'and maybe ./some*/star/*/*path.js';// again without spaces

  /**!
   * ignored indented
   * block comment
   */
  function url(that /* have url http://url.com here */) {};

  /* indented oneline block comment */
  var faz = 'and ./globstar/path/to/**/*.js source';
};

/* oneline block comment before variable */
var bar = true; /* oneline block comment after variable */

//! ignored oneline line comment before variable
var baz = 'oneline block /* comment in */ string';

/**
 * multiline block comment
 * with url http://github.com
 * @type {String}
 */
var qux = 'globstar-like ./path/to/*/some/file.js here';


/*!
 * ignored not indented
 * block comment
 * @type {String}
 */
var fuz = 'some //line comment in string'; // line comment after variable

// here some
// multiline
// line comment
var _with = 'leading  //                    whitespace should be stripped';

var globstar = 'one ./glob/star/*/*like*/*.js more'; // some long; text with 'single-quotes' here

// globstar in line
// comment ./globstar/path/to/**/*.js source
var again = 'fake ./some*/star/*/*path.js here';

// oneline line comment with http://url.com
var url = 'line comment in string // with http://some.url.com'; //! ignored line comment

```

**runner.js**

``` js
var fs = require('fs');

// yesterday's regexes
// var reBlock = /\/\*(?!\/)(?:[\S\s\W\w]+?)\*\//gm
// var reBlockIgnore = /\/\*(?!(\*?\/|\*?\!))(?:[\S\s\W\w]+?)\*\//gm
// var reLine = /(?:^|\s)\/\/([\S\s\W\w]+?)$/gm
// var reLineIgnore = /(?:^|\s)\/\/(?!\!)([\S\s\W\w]+?)$/gm

// today regexes
var reBlock = /(?:^|\s)(?:\/\*(?!\*?\/)(?:[\S\s]+?)\*\/)/gm
var reBlockIgnore = /(?:^|\s)(?:\/\*(?!(\*?\/|\*?\!))(?:[\S\s]+?)\*\/)/gm
var reLine = /(?:^|\s?)\/\/([^\\;]+?)$/gm
var reLineIgnore = /(?:^|\s?)\/\/(?!\!)([^\\;]+?)$/gm

var fixture = fs.readFileSync('./fixture.js', 'utf-8')

var actualBlock = fixture.replace(reBlock,'')
var actualBlockIgnore = fixture.replace(reBlockIgnore,'')

var actualLine = fixture.replace(reLine,'')
var actualLineIgnore = fixture.replace(reLineIgnore,'')

var actualAll = actualBlock.replace(reLine,'')


console.log(actualAll)
```

**Running it, we have almost what we expect, except that it not removes line comments that are indented and one block comment that is in string.**

**Comment by sindresorhus** [comment]
Relevant: https://github.com/sindresorhus/comment-regex/issues/1

**Comment by tunnckoCore** [comment]
~~Holy shit, I did it. LOL
Fix the issue with line comments.~~

``` js
/(?:^|[^:]\s?)\/\/([^'"]+?)$/gm // pass almost, except `code; // some "text" 'and' here`
```

**Comment by tunnckoCore** [comment]
``` js
/(?:^|[^:]\s?)\/\/([^;]+?)$/gm // pass almost, except `code; // wtf; yeah fails`
```

> So we have to decide which is the less used symbol, lol. This is the easiest way, imo.
> As @sindresorhus said it "it will never be totally foolproof as that impossible with just regex"

**Comment by tunnckoCore** [comment]
@blakeembrey @sindresorhus @contra @jonschlinkert @mk-pmb
When Im thinking... Its impossible to solve/stop this madness, lol.

Because if we solve only issue with block comments (in strings like this one below)

``` js
var baz = 'oneline block /* comment in */ string';
```

will have to give up from

``` js
var foo = function foo(oneline, /* block comment in */ func) {}
```

Or Im in wrong way?

**Comment by tomByrer** [comment]
Everybody has their own workflow, but I find http://regexr.com/ helpful to quickly test.  Just takes dedication to add all test cases.

**Comment by blakeembrey** [comment]
You can write a regexp to match this stuff but you need to run it recursively and it can't just be dropped into any `String#match` call. For example:

``` js
/(?:\\.|"(?:\\.|[^"])*?"|'(?:\\.|[^'])*?'|[^'"])*?(\/\*[\s\S]*?\*\/)/.exec('code "/* string \\" */" /* comment */');
//=> ["code "/* string \" */" /* comment */", "/* comment */"]

/(?:\\.|"(?:\\.|[^"])*?"|'(?:\\.|[^'])*?'|[^'"])*?(\/\/.*)/.exec('code "// string" // comment "stuff"');
//=> ["code "// string" // comment "stuff"", "// comment "stuff""]
```

However, it kind of defeats the purpose of a module called [comment-regex](https://github.com/sindresorhus/comment-regex). I'd be open to turning this into a helper module though.

**Comment by tunnckoCore** [comment]
> I find http://regexr.com/ helpful to quickly test

Yea and I also use http://www.gethifi.com/tools/regex

**Comment by tunnckoCore** [comment]
More pretty look. https://github.com/regexps/code-comments-regex to test it.

**Comment by jonschlinkert** [comment]
closing so we can move this discussion to respective repos for code comments - code comment repos will need to be more specific (e.g. one for line, one for block etc). Also, please don't create a repo until we decide on conventions (I created two un=populated repos by way of example, for those discussions)

**Comment by tunnckoCore** [comment]
Yep. I just thinking to close it.

But one side question. Want to PR `code-comments-regex` to `strip-comments` (or as new branch) to review it?

**Comment by jonschlinkert** [comment]
No, thanks. But like I mentioned in another post I already have parse-comments, extract-comments, and strip-comments repos. Might make more sense for parse comments when the next version is released (it allows custom plugins for parsing params, like we're doing with remarkable)

**Comment by tomByrer** [comment]
> please don't create a repo until we decide on conventions

Good idea, thanks!
