### ISSUE TITLE
regex-utc-date

### ISSUE THREAD

**Issue by yoshuawuyts** [regexhq/regexhq#8]
Would you be interested in having [`regex-utc-date`](https://github.com/yoshuawuyts/regex-utc-date) in here? Thanks!

**Comment by tunnckoCore** [comment]
Of course, why not.

**Comment by yoshuawuyts** [comment]
Nice! Can you add me to the org so I can pull the repo in?

**Comment by tunnckoCore** [comment]
O yea yea, no prob.

Maybe and others @regexps/owners to say thoughts

**Comment by johno** [comment]
:+1:

**Comment by yoshuawuyts** [comment]
https://github.com/regexps/regex-utc-date :tada:
